#!/bin/bash
repo=https://raw.githubusercontent.com/tukimax/permission/main/ip
ipsaya=$(wget -qO- ipinfo.io/ip);
data_server=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
date_list=$(date +"%Y-%m-%d" -d "$data_server")
useexp=$(wget -qO- ${repo} | grep $ipsaya | awk '{print $4}')
 if [[ $date_list < $useexp ]]; then
    echo -ne
 else
    exit
 fi

MYIP=$(wget -qO- ipinfo.io/ip)
REPO='https://package-9q1.pages.dev/'
idc='https://upload-dla.pages.dev/'
start=$(date +%s)
# funcional
function print_install() {
	echo -e "${Green} ┌──────────────────────────────────────────┐ ${FONT}"
    echo -e "${YELLOW} # Memasang $1 "
	echo -e "${Green} └──────────────────────────────────────────┘ ${FONT}"
    sleep 2
    clear
}

function print_success() {
	echo -e "${Green} ┌──────────────────────────────────────────┐ ${FONT}"
    echo -e "${YELLOW} # $1 berhasil dipasang"
	echo -e "${Green} └──────────────────────────────────────────┘ ${FONT}"
    sleep 2
    clear
}

### Pasang OpenVPN
    print_install "OpenVPN"
    wget -O /etc/pam.d/common-password "${REPO}config/common-password" >/dev/null 2>&1
    chmod +x /etc/pam.d/common-password
    wget -O /root/.config/rclone/OPENVPN "https://raw.githubusercontent.com/tukimax/permission/main/OPENVPN" >/dev/null 2>&1 
    bash /root/.config/rclone/OPENVPN | tee /root/install.log
    print_success "OpenVPN"

### Pasang SlowDNS
    print_install "SlowDNS"
    wget -O /tmp/ndm "https://raw.githubusercontent.com/tukimax/permission/main/NSDOMAIN" >/dev/null 2>&1
    bash /tmp/ndm && rm /tmp/ndm
	cd
	NS=$(cat /etc/xray/dns)
	wget -O /etc/slowdns/dnstt-server "${REPO}core/dnstt-server" >/dev/null 2>&1
	chmod +x /etc/slowdns/dnstt-server >/dev/null 2>&1
	/etc/slowdns/dnstt-server -gen-key -privkey-file /etc/slowdns/server.key -pubkey-file /etc/slowdns/server.pub
	chmod +x /etc/slowdns/*
	wget -O /etc/systemd/system/server.service "${REPO}service/server.service" >/dev/null 2>&1
	sed -i "s/xxxx/$NS/g" /etc/systemd/system/server.service
    sleep 2
    print_success "SlowDNS"

### Pasang BadVPN
    # > BadVPN
    print_install "BadVPN"
    wget -O /usr/sbin/badvpn "${REPO}core/badvpn" >/dev/null 2>&1
    wget -q -O /etc/systemd/system/badvpn1.service "${REPO}service/badvpn1.service" >/dev/null 2>&1
    wget -q -O /etc/systemd/system/badvpn2.service "${REPO}service/badvpn2.service" >/dev/null 2>&1
    wget -q -O /etc/systemd/system/badvpn3.service "${REPO}service/badvpn3.service" >/dev/null 2>&1
    chmod +x /usr/sbin/badvpn > /dev/null 2>&1 
    print_success "BadVPN"

### Pasang Custom    
    # > Add UDPCustom
    print_install "Udp-Custom"
    echo " ----->> Downloading Toll UdpCustom........"
    sleep 1
    wget -q --show-progress --load-cookies /tmp/cookies.txt "${REPO}core/custom" -O /usr/sbin/custom >/dev/null 2>&1
    rm -rf /tmp/cookies.txt
    chmod +x /usr/sbin/custom
    echo " ----->> Please Waiting Proses Downloading Default Config UdpCustom........"
    sleep 1
    wget -q --show-progress --load-cookies /tmp/cookies.txt "${REPO}config/config.json" -O /root/.config/udp/config.json >/dev/null 2>&1
    rm -rf /tmp/cookies.txt
    chmod 644 /root/.config/udp/config.json
    sleep 1

if [ -z "$1" ]; then
cat <<EOF > /etc/systemd/system/custom.service
[Unit]
Description=UDP Custom by MakhlukVpn

[Service]
User=root
Type=simple
ExecStart=/usr/sbin/custom server
WorkingDirectory=/root/.config/udp/
Restart=always
RestartSec=2s

[Install]
WantedBy=default.target
EOF
else
cat <<EOF > /etc/systemd/system/custom.service
[Unit]
Description=UDP Custom

[Service]
User=root
Type=simple
ExecStart=/usr/sbin/custom server -exclude $1
WorkingDirectory=/root/.config/udp/
Restart=always
RestartSec=2s

[Install]
WantedBy=default.target
EOF
fi

    print_success "Udp-Custom"

### Pasang Psiphon
    # > Add Psiphon
    wget -O /root/.config/psiphon/psiphon "https://github.com/Psiphon-Labs/psiphon-tunnel-core-binaries/raw/master/psiphond/psiphond" >/dev/null 2>&1
    cd /root/.config/psiphon && chmod +x psiphon
    ./psiphon --ipaddress ${MYIP} --web 3000 --protocol SSH:3001 --protocol OSSH:3002 --protocol FRONTED-MEEK-OSSH:8443 generate
    wget -O /etc/systemd/system/psiphon.service "${REPO}service/psiphon.service" >/dev/null 2>&1
    mv psiphon /usr/sbin && cd
    cp /root/.config/psiphon/*.dat /var/www/html/psiphon.txt

### Pasang Menu
    # > Add menu
    mkdir -p /tmp/menu
    wget -O /tmp/menu/menu.zip "https://raw.githubusercontent.com/tukimax/permission/main/menu.zip" >/dev/null 2>&1
    cd /tmp/menu && unzip menu.zip >/dev/null 2>&1
    rm menu.zip && chmod +x * && cd
    mv /tmp/menu/* /usr/sbin/

### Pasang Web 
    # > Add Web
    wget -O /var/www/html/web.zip "${idc}last/web.zip" >/dev/null 2>&1
    cd /var/www/html/ && unzip web.zip >/dev/null 2>&1 
    cd && rm /var/www/html/web.zip
   
### Pasang Bot
    # > pasang bot xolpanel
    apt install python3 python3-pip git
    wget -O /root/.config/panel.zip "https://raw.githubusercontent.com/tukimax/permission/main/panel.zip" >/dev/null 2>&1
    cd /root/.config && unzip panel.zip >/dev/null 2>&1
    rm panel.zip && mv xolpanel/shell.zip /etc/shell
    cd /etc/shell && unzip shell.zip >/dev/null 2>&1
    chmod 755 * && rm shell.zip && cd
    wget -O /etc/systemd/system/xolpanel.service "${REPO}service/xolpanel.service" >/dev/null 2>&1
